### ISSUE TITLE
prod docker image: webpack assets

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#101]
We are installing bpaotu in non-development mode, but the webpack assets get strandded in /app and aren't copied in.

Not sure as to the fix, it's possible we will want to change things so that they are copied in.

**Comment by grahame** [comment]
I've put a workaround in place (serving them out of /app)

**Comment by sztamas** [comment]
Fixed by https://github.com/BioplatformsAustralia/bpaotu/commit/3dd423077c6556b2cecef51e1160cbbda6c3ebf8

**Comment by sztamas** [comment]
@grahame can you please remove the workaround?

I've also looked at the build scripts and there is some serious fishiness going on in there.
We pip install the package, but then include all the source file in `/app` as well.

Looks very suspect to me.
