### ISSUE TITLE
BIOM export support

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#17]
Export data in the BIOM format (hdf5)

http://biom-format.org/

We can't stream BIOM data, so we'll need to prepare it on the server and then email the person a link.

Start off by reviewing the BIOM format docs, and then come back with a proposed way to add this support. We must keep the current CSV format support, this is an additional feature.

Note this is required for the RDC project to move forward.

**Comment by grahame** [comment]
Note - there is a card in the RDC project for this.

**Comment by schangccg** [comment]
PR: https://github.com/BioplatformsAustralia/bpaotu/pull/39

Implemented.
