### ISSUE TITLE
Plots function capturing sentry values

### ISSUE THREAD

**Issue by abissett** [BioplatformsAustralia/bpaotu#219]
The plots function in the search tools is treating sentry values as numbers instead of NAN, making the plots appeared skewed to large negative values.   For example, see Salinity plot from marine samples.

**Comment by hou098** [comment]
e.g. -9999 for salinity

![Screenshot_2022-06-03_16-41-17](https://user-images.githubusercontent.com/93953122/171801151-bd9d3b5a-41ef-4023-abae-e2ba1ba73c76.png)

**Comment by hou098** [comment]
Also, plots for free-text fields are bogues. For example `samp_collect_device` has the values
```
 '0.2um filter', '1.1', '1.17', '1.18', '1.2', '1.4', '1.5.1', '1.5.2',
 'CTD', 'ISP', 'Tow-fish', 'soil corer'
```
with frequencies
```
 8, 374, 187, 292, 1, 1956, 155, 125, 44, 15, 6, 64
```
in this test case, and the plot seems to try and interpret every string as numeric and ignores the rest.
![Screenshot_2022-06-06_11-52-16](https://user-images.githubusercontent.com/93953122/172081740-af6d049a-8fab-47f1-be50-d8753b07be8d.png)

**Comment by hou098** [comment]
Plot for `sample_site_location_description`, which is typically a place name, but sometimes just digits.

![Screenshot_2022-06-06_12-03-19](https://user-images.githubusercontent.com/93953122/172082670-74d22683-0150-4d81-aaff-454629d03fb0.png)
