### ISSUE TITLE
Amplicon selection is carried over to metagenome selection

### ISSUE THREAD

**Issue by Smithmania** [BioplatformsAustralia/bpaotu#233]
switching from amplicon search mode to metagenome mode, the Interactive graph search retains the amplicon type as a filter e.g., Amplicon <is> ITS1FITS4_fungi_ITS1. With the taxonomy selection being metaxa

I think the following behaviour is associated ...  
Selecting interactive graph brings up graphs for the search (amplicon, taxonomy etc) but selection of taxonomy from the dropdown and using the interactive graph search results in the spinning DNA icon for a long time, I used the search:
Kingdom is Bacteria
Phylum is Cyanobacteria
Class is Cyanobacteria
Order is Subgroup1

If you clear the taxonomy search the Amplicon filter is removed and the search options appear too be normal behaviour

**Comment by hou098** [comment]
I'm pretty sure this is cosmetic: i.e. the amplicon filter is displayed but has no effect in metagenome mode. That means it should be easy to fix.

**Comment by Smithmania** [comment]
I think there could be something else going on. If you try the same search I did above I get the spinning double helix that goes on forever. The same search on the amplicon page with metaxa selected as the amplicon the search is snappy. It also seems to run ok on both the metagenome and amplicon pages on http://oa-74-cdc.it.csiro.au:3000/

**Comment by Smithmania** [comment]
It looks like its hanging because `order subgroup1` isnt contained in the samples loaded into the metagenome section. So the selections for the metaxa taxonomy dropdowns are based on the whole metaxa dataset

**Comment by hou098** [comment]
OK, looks like separate bug. 
See https://github.com/BioplatformsAustralia/bpaotu/issues/234

**Comment by hou098** [comment]
Fixed by https://github.com/BioplatformsAustralia/bpaotu/commit/e3f3a20cb15347de2ac24ae7f06dee8f47575477
