### ISSUE TITLE
Add metadata download option for metagenome search results

### ISSUE THREAD

**Issue by Smithmania** [BioplatformsAustralia/bpaotu#248]
Can we add functionality to download metadata for samples returned from the metagenome searches - we do this for the amplicons. Not sure where the best place for the download option is it could be in the same spot as we do for the amplicons or it could be included as a checkbox in the metagenome fetcher

**Comment by hou098** [comment]
Do you mean something like the "Download Contextual Data only (CSV)" button?

**Comment by Smithmania** [comment]
yep something like that or as part of your bulk download packet - not sure what makes most sense from a user perspective if it came as part of the download packet by default (with the option of adding other files of interest) all the data would be together for the one search

**Comment by hou098** [comment]
I think the the best option might be to implement the "Download Contextual Data only (CSV)" button on the metagenome tab too.That would maintain consistency with the amplicon search interface and behaviour — see https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by hou098** [comment]
Implemented in https://github.com/BioplatformsAustralia/bpaotu/tree/1.36.0
