### ISSUE TITLE
Search Results table header are column names not display names

### ISSUE THREAD

**Issue by drollins** [BioplatformsAustralia/bpaotu#269]
Values are still fine for ontology columns

![Screenshot from 2023-05-31 11-25-00](https://github.com/BioplatformsAustralia/bpaotu/assets/715114/c6ff2903-fbdd-42a3-bb2b-9c026e3e168e)

**Comment by drollins** [comment]
Fixed with tutorial updates

**Comment by abissett** [comment]
test
