### ISSUE TITLE
Contextual metadata query bug

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#38]
Reported by Anna Fitzgerald:

If you query the database for "Broad Land Use" - "Conservation and Natural Environments  - National Park" and then hit search, no results are found.

That's suspicious - we need to look into why there are no matches.

Ideally, the hierarchy in this ontology should be respected when querying. So searching for "Conservation and Natural Environments" should return all samples which have that key set, or any of the child keys. This may mean that we need to change the ontology columns from integer type to a set type, so we can do "IN" queries on the column.

**Comment by schangccg** [comment]
@grahame has discovered that this is not a bug. :smile:
