### ISSUE TITLE
Improve filenames for data downloads

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#40]
Make the filenames for the Zip export of OTU data (CSV and BIOM) meaningful.

 - [x] improve the outer filename (the .zip)
 - [x] improve the inner filename (only applicable to BIOM)

Perhaps we should just include the date and time in ISO format, with a sensible prefix. So, 'BiomExport-20180524T1406.zip'. Note we drop the colons from the ISO format as they'll cause problems on macOS.

**Comment by grahame** [comment]
@schangccg could you please take a look at this when you have a moment?

**Comment by schangccg** [comment]
pr: https://github.com/BioplatformsAustralia/bpaotu/pull/42

**Comment by grahame** [comment]
Looks good, thanks Sam.
