### ISSUE TITLE
Incompatible BIOM file for phyloseq

### ISSUE THREAD

**Issue by mthang** [BioplatformsAustralia/bpaotu#44]
Phyloseq Installation
https://joey711.github.io/phyloseq/install.html
source('http://bioconductor.org/biocLite.R')
biocLite('phyloseq')

The phyloseq uses import_biom to import BIOM file.
e.g., 
x<-import_biom("GP.biom")

An issue occur when using the same feature to import the following biom file.

x<-import_biom("json_biom_file.biom")

Error in dimnames(x) <- dn :
  length of 'dimnames' [2] not equal to array extent
In addition: There were 50 or more warnings (use warnings() to see the first 50)

Warning messages:
1: In parseFunction(i$metadata$taxonomy) : Empty taxonomy vector encountered.
2: In parseFunction(i$metadata$taxonomy) : Empty taxonomy vector encountered.
3: In parseFunction(i$metadata$taxonomy) : Empty taxonomy vector encountered.
4: In parseFunction(i$metadata$taxonomy) : Empty taxonomy vector encountered.
....

Some phyloseq users have posted the same issue here.
https://github.com/joey711/phyloseq/issues/674

**Comment by grahame** [comment]
Tracked down; by convention, the taxonomy assignment should be in the 'taxonomy' key of the 'row' metadata object, in an Array, from kingdom down.

http://biom-format.org/documentation/format_versions/biom-1.0.html

**Comment by grahame** [comment]
Using Jeff's test case:

```
Selected: Amplicon=27f519r_bacteria; Kingdom = Bacteria; Phylum = Bacteria_unclassified; Environment = Soil.
```
