### ISSUE TITLE
Current user (email address) no longer shown 

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#49]
This happened when we moved to React, it should be simple to add this feature back in. I'll take a look, it'd be good to get across the new React stuff anyway!

Reported by Jeff from QCIF.

**Comment by sztamas** [comment]
@grahame I left that feature out on purpose until we put the header/footer of the page in React as well.
I thought I will do it when we add react router to the picture, but you can just start with moving the header or the header and the footer into the React app and we'll add react router later on.

**Comment by grahame** [comment]
@sztamas  cool - @jhchristiansen mentioned it was something he used all the time (I think he has multiple galaxy accounts, and it seemed like a nice little thing for me to do to to get my head around the new code.

**Comment by sztamas** [comment]
@grahame I've added React router, moved the header/footer into the React app and as I was already working on that I've added the user's email to the header as well.

**Comment by grahame** [comment]
This is fixed.
