### ISSUE TITLE
Drop empty contextual metadata columns from the CSV export

### ISSUE THREAD

**Issue by grahame** [BioplatformsAustralia/bpaotu#79]
If you subset the data (e.g. to just environment = Soil), many of the contextual metadata fields become irrelevant and will be blank for all samples.

We already deal with this in the biom export, by doing a first pass to determine the interesting fields, and then writing only those fields into the BIOM file. We need to do the same thing for the CSV export code.

Take a look at the code and have a go at making the change. If you look at `biom.py` you'll see how we approach the issue for the other output format.

**Comment by grahame** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [OTU export (CSV) - remove blank columns from contextual metadata](https://trello.com/c/CtQfzj5H/60-otu-export-csv-remove-blank-columns-from-contextual-metadata)

**Comment by krupalip** [comment]
PR Submitted - https://github.com/BioplatformsAustralia/bpaotu/pull/80
feature branch - https://github.com/BioplatformsAustralia/bpaotu/tree/drop_empty_contextual_columns

**Comment by grahame** [comment]
Landed by Krupali
